##
## This workflow handles testing of pull requests and pushes.
## It also publishes some packages to any new Erlang/OTP release
##
## To speed this up it would be nice if one could share docker
## images inbetween different jobs, but at the moment this is
## not possible so we need to rebuild all of Erlang/OTP multiple
## times.
##
## When ghcr.io support using the GITHUB_TOKEN we should migrate
## over to use it instead as that should allow us to use the
## built-in caching mechanisms of docker/build-push-action@v2.
## However as things are now we use docker directly to make things
## work.
##

name: Build and check Erlang/OTP

on:
  push:
  pull_request:

env:
    ## Equivalent to github.event_name == 'pull_request' ? github.base_ref : github.ref_name
    BASE_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}

jobs:

  pack:
    name: Build Erlang/OTP (64-bit)
    runs-on: ubuntu-latest
    outputs:
        BASE_BUILD: ${{ steps.base-build.outputs.BASE_BUILD }}
        changes: ${{ steps.changes.outputs.changes }}
        all: ${{ steps.apps.outputs.all }}
    steps:
      - uses: actions/checkout@v3
      - name: Get applications
        id: apps
        run: |
          .github/scripts/path-filters.sh > .github/scripts/path-filters.yaml
          ALL_APPS=$(grep '^[a-z_]*:' .github/scripts/path-filters.yaml | sed 's/:.*$//')
          ALL_APPS=$(jq -n --arg inarr "${ALL_APPS}" '$inarr | split("\n")' | tr '\n' ' ')
          echo "all=${ALL_APPS}" >> $GITHUB_OUTPUT
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/scripts/path-filters.yaml
      - name: Create initial pre-release tar
        run: .github/scripts/init-pre-release.sh otp_archive.tar.gz
      - name: Upload source tar archive
        uses: actions/upload-artifact@v3
        with:
          name: otp_git_archive
          path: otp_archive.tar.gz
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache BASE image
        uses: actions/cache@v3
        with:
            path: otp_docker_base.tar
            key: ${{ runner.os }}-${{ hashFiles('.github/dockerfiles/Dockerfile.ubuntu-base', '.github/scripts/build-base-image.sh') }}
      - name: Build BASE image
        run: .github/scripts/build-base-image.sh "${BASE_BRANCH}" 64-bit
      - name: Cache pre-built tar archives
        id: pre-built-cache
        uses: actions/cache@v3
        with:
            path: |
                otp_src.tar.gz
                otp_cache.tar.gz
            key: prebuilt-${{ github.ref_name }}-${{ github.sha }}
            restore-keys: |
                prebuilt-${{ github.base_ref }}-${{ github.event.pull_request.base.sha }}
      - uses: dorny/paths-filter@v2
        id: cache
        with:
          filters: |
              no-cache:
                  - '.github/**'
              deleted:
                  - deleted: '**'
              bootstrap:
                  - 'bootstrap/**'
              configure:
                  - '**.ac'
                  - '**.in'
          list-files: shell
      - name: Restore from cache
        env:
            NO_CACHE: ${{ steps.cache.outputs.no-cache }}
            BOOTSTRAP: ${{ steps.cache.outputs.bootstrap }}
            CONFIGURE: ${{ steps.cache.outputs.configure }}
        run: |
            .github/scripts/restore-from-prebuilt.sh "`pwd`" \
              "`pwd`/.github/otp.tar.gz" \
              "`pwd`/otp_archive.tar.gz" \
              '${{ github.event_name }}' \
              '${{ steps.cache.outputs.deleted_files }}' \
              '${{ steps.changes.outputs.changes }}'
      - name: Upload restored cache
        uses: actions/upload-artifact@v3
        if: runner.debug == 1
        with:
          name: restored-cache
          path: .github/otp.tar.gz
      - name: Build image
        run: |
          docker build --tag otp \
            --build-arg MAKEFLAGS=-j$(($(nproc) + 2)) \
            --file ".github/dockerfiles/Dockerfile.64-bit" \
            .github/
      - name: Build pre-built tar archives
        run: |
          docker run -v $PWD:/github --entrypoint "" otp \
            scripts/build-otp-tar -o /github/otp_clean_src.tar.gz /github/otp_src.tar.gz -b /buildroot/otp/ /github/otp_src.tar.gz
      - name: Build cache
        run: |
          if [ -f otp_cache.tar.gz ]; then
            gunzip otp_cache.tar.gz
          else
            docker run -v $PWD:/github --entrypoint "" otp \
              bash -c 'cp ../otp_cache.tar /github/'
          fi
          docker run -v $PWD:/github --entrypoint "" otp \
            bash -c 'set -x; C_APPS=$(ls -d ./lib/*/c_src); find Makefile ./make ./erts ./bin/`erts/autoconf/config.guess` ./lib/erl_interface ./lib/jinterface ${C_APPS} `echo "${C_APPS}" | sed -e 's:c_src$:priv:'` -type f -newer README.md \! -name "*.beam" \! -path "*/doc/*" | xargs tar --transform "s:^./:otp/:" -uvf /github/otp_cache.tar'
          gzip otp_cache.tar
      - name: Upload pre-built tar archive
        uses: actions/upload-artifact@v3
        with:
          name: otp_prebuilt
          path: |
              otp_src.tar.gz
              otp_cache.tar.gz
         
  build-s390x:
    name: Build Erlang/OTP (s390x)
    runs-on: ubuntu-20.04
    needs: pack
    steps:
      - uses: actions/checkout@v3

      - name: Download source archive
        uses: actions/download-artifact@v3
        with:
          name: otp_prebuilt

      - name: Run build 
        uses: uraimo/run-on-arch-action@v2.3.0
        with:
          arch: s390x
          distro: ubuntu20.04
          run: | 
            apt-get update && \
            apt-get install -y --no-install-recommends curl autoconf fop flex gawk gcc g++ gzip libncurses-dev libssl-dev \
            libxml2-utils make tar unixodbc-dev wget xsltproc pkg-config 
            mkdir -p /opt/java
            wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.17_8.tar.gz
            tar -C /opt/java -xzf OpenJDK11U-jdk_s390x_linux_hotspot_11.0.17_8.tar.gz --strip 1
            export JAVA_HOME=/opt/java
            export PATH=$JAVA_HOME/bin:$PATH
            java -version
            tar -xzf ./otp_src.tar.gz
            cd otp
            ./configure && make && make install
            ./bin/erl -noshell -eval 'io:format("~s", [erlang:system_info(system_version)]), halt().'
            ./bin/erl -noshell -eval 'ok = crypto:start(), io:format("crypto ok~n"), halt().'
